run-title: Harlow_0
seed: 1111
save-path: /home/bkhmsi/Documents/Projects/lab/Meta-RL-Harlow/ckpt
log-path: /home/bkhmsi/Documents/Projects/lab/Meta-RL-Harlow/logs
save-interval: 500
print-interval: 100
resume: false
start-episode: 15_000
train: true
test: true
mode: episodic # {incremental, episodic}

task:
  imsize: 34
  max-length: 3600
  num-trials: 6 # 3600 steps

  num-actions: 3
  action-repeat: 4
  decision-per-trial: 3

  train-episodes: 100_000 
  test-episodes: 500

agent:
  mem-units: 256
  dict-len: 100_000
  dict-kernel: cosine

  n-workers: 1
  share-optim: true
  
  value-loss-weight: 0.4
  entropy-weight: 0.001
  max-grad-norm: 0.
  
  gamma: .91
  lr: 7.5e-4
  weight-decay: 0

  lstm-unroll: 100

