run-title: HSE_1
load-title: HarlowSimple_3_1
seed: 1234
device: cpu
save-path: /home/bkhmsi/Documents/Projects/lab/Meta-RL-Harlow/ckpt
log-path: /home/bkhmsi/Documents/Projects/lab/Meta-RL-Harlow/logs_ep_2
load-path: ckpt/HarlowSimple_11_1/HarlowSimple_11_1_0_5000.pt
save-interval: 500
resume: false
start-episode: 0 
optimizer: rmsprop # {rmsprop, adam}
train: true
test: true
mode: episodic # {vanilla, vanilla-episodic, episodic}

task:
  max-length: 250
  num-trials: 6
  num-actions: 3
  input-dim: 13

  train-episodes: 2500 
  test-episodes: 500

agent:
  mem-units: 256

  dict-len: 10_000
  dict-kernel: cosine

  n-workers: 1
  share-optim: true
  
  value-loss-weight: 0.4
  entropy-weight: 0.001
  max-grad-norm: 0.
  
  gae-lambda: 1.
  gamma: .91
  lr: 7.5e-4
  weight-decay: 0

  n-step-update: 20 

